import * as dotenv from 'dotenv'
dotenv.config()

const env = {
  PORT: process.env.PORT,
  MYSQL_DATABASE: process.env.MYSQL_DATABASE,
  GOOGLE_DRIVE_CLIENT_ID: process.env.GOOGLE_DRIVE_CLIENT_ID,
  GOOGLE_DRIVE_CLIENT_SECRET: process.env.GOOGLE_DRIVE_CLIENT_SECRET,
  GOOGLE_DRIVE_REDIRECT_URI: process.env.GOOGLE_DRIVE_REDIRECT_URI,
  GOOGLE_DRIVE_REFRESH_TOKEN: process.env.GOOGLE_DRIVE_REFRESH_TOKEN,
  GOOGLE_DRIVE_FORDER_ID: process.env.GOOGLE_DRIVE_FORDER_ID
}

export default env
