import * as dotenv from 'dotenv'
dotenv.config()

const env = {
  NODE_ENV: process.env.NODE_ENV ?? 'development',
  PORT: process.env.PORT,
  MYSQL_DATABASE: process.env.MYSQL_DATABASE,
  GOOGLE_DRIVE_CLIENT_ID: process.env.GOOGLE_DRIVE_CLIENT_ID,
  GOOGLE_DRIVE_CLIENT_SECRET: process.env.GOOGLE_DRIVE_CLIENT_SECRET,
  GOOGLE_DRIVE_REDIRECT_URI: process.env.GOOGLE_DRIVE_REDIRECT_URI,
  GOOGLE_DRIVE_REFRESH_TOKEN: process.env.GOOGLE_DRIVE_REFRESH_TOKEN,
  GOOGLE_DRIVE_FORDER_ID: process.env.GOOGLE_DRIVE_FORDER_ID,
  KEY_SESSION: process.env.KEY_SESSION,
  AUTH_SECRET_KEY_ACCESS_TOKEN: process.env.AUTH_SECRET_KEY_ACCESS_TOKEN,
  AUTH_SECRET_KEY_REFRESH_TOKEN: process.env.AUTH_SECRET_KEY_REFRESH_TOKEN,
  AUTH_SECRET_KEY_EXPIRES: process.env.AUTH_SECRET_KEY_EXPIRES,
  AUTH_REFRESH_KEY_EXPIRES: process.env.AUTH_REFRESH_KEY_EXPIRES,
  REDIS_HOST: process.env.REDIS_HOST,
  REDIS_PORT: process.env.REDIS_PORT
}

export default env
